### ISSUE TITLE
Doesn't work when `flutter` command is not available

### ISSUE THREAD

**Issue by dumazy** [dumazy/kerekewere#8]
It looks like `custom_lint` requires the `flutter` command to be available.
To check if there is something we can do about this.

This issue was reproduced using FVM 2.4.1, which doesn't expose the `flutter` command but only works through `fvm flutter`.

```
The request analysis.setContextRoots failed with the following error:
RequestErrorCode.PLUGIN_ERROR
ProcessException: No such file or directory
  Command: flutter pub get
at:
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      CustomLintWorkspace.runPubGet (package:custom_lint/src/workspace.dart:772:36)
#5      CustomLintWorkspace.resolvePluginHost (package:custom_lint/src/workspace.dart:765:11)
#6      SocketCustomLintServerToClientChannel._startProcess (package:custom_lint/src/v2/server_to_client_channel.dart:151:24)
#7      SocketCustomLintServerToClientChannel.init (package:custom_lint/src/v2/server_to_client_channel.dart:110:22)
#8      CustomLintServer._maybeSpawnCustomLintPlugin (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:394:25)
<asynchronous suspension>
#9      CustomLintServer._handleAnalysisSetContextRoots.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:341:9)
<asynchronous suspension>
#10     PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#11     CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:173:22)
<asynchronous suspension>
```

**Comment by JeffreyDeNeve** [comment]
Using `custom_lint v0.6.7` and `subpackage_lint v1.2.0` in combination with `fvm v2.4.1` didn't seem to work.

Updated `fvm` to `v3.2.1`. That didn't automatically fix it, but was probably needed!
Then tried a combination of the following things:

- Execute `dart pub global activate fvm`
- Ensure `$HOME/.pub-cache/bin` and `$HOME/fvm/default/bin` were in my $PATH
- Executed command `Dart: Restart Analysis Server` in VsCode
- Restart VsCode
- Restart computer
- Possibly other things that I forgot

After restarting my device, the linting was working with the latest version of the packages! It is possible that restarting your device after updating fvm is sufficient.
